# Generated by Django 6.0.4 on 2026-07-30 12:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0007_studentprofile_last_scanned_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_subjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomMovementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entered Class'), ('OUT', 'Left Class')], max_length=10)),
                ('reason', models.CharField(blank=True, help_text='e.g. Restroom, Lab visit, Home leave', max_length=200, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_logs', to='coaching.studentprofile')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_movements', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coaching.subject')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('notebook', 'Notebook Correction'), ('assignment', 'Assignment / Homework'), ('project', 'Project Work'), ('test', 'Class Test / Exam')], default='notebook', max_length=20)),
                ('title', models.CharField(help_text='e.g. Chapter 4 Homework or Science Project', max_length=200)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_marks', models.DecimalField(blank=True, decimal_places=2, default=100.0, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted for Correction'), ('verified', 'Verified & Returned to Student'), ('resubmit', 'Needs Resubmission')], default='verified', max_length=20)),
                ('teacher_remarks', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='coaching.studentprofile')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_corrections', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coaching.subject')),
            ],
            options={
                'ordering': ['-verified_at'],
            },
        ),
    ]
