# Generated by Django 6.0.4 on 2026-07-30 16:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0008_subject_classroommovementlog_assignmentcorrection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=35000.0, max_digits=10, verbose_name='Total Course Fee'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='daily_note',
            field=models.TextField(blank=True, help_text='Daily teacher tip, assignment, or announcement for the section', null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Section Name'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_time',
            field=models.TimeField(default='09:00:00', help_text='Section start time'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='coaching.batch', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Legacy monthly fee reference', max_digits=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='next_due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PeriodSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(help_text='e.g. Period 1', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='coaching.batch', verbose_name='Section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='coaching.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time_in', models.TimeField(auto_now_add=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='present', max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time_in'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'date'), name='unique_teacher_daily_attendance')],
            },
        ),
    ]
