# Generated by Django 6.0.4 on 2026-07-31 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0009_alter_batch_options_studentprofile_total_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_batches', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Section Teacher'),
        ),
    ]
